---
- name: reload nginx
  service:
    name: nginx
    state: reloaded

- name: restart django
  systemd:
    name: myapp
    state: restarted

- name: restart gunicorn
  systemd:
    name: gunicorn
    state: restarted
    enabled: yes