services:
  web:
    build: .
    ports:
      - 8000:8000
    env_file: env
    environment:
      - MIGRATE_AND_CREATE_USER_ON_STARTUP=True
    depends_on:
      - db
    networks:
      - application

  db:
    image: postgres:17.5-alpine
    ports:
      - 5432:5432
    env_file: env
    volumes:
      - postgres_db:/var/lib/postgresql/data
    networks:
      - application

networks:
  application:
    driver: bridge
volumes:
  postgres_db: