---
- name: Print EC2 public IP from inventory
  debug:
    msg: "{{ inventory_hostname }}"

- name: Update yum cache
  yum:
    update_cache: yes

- name: Create app directory
  file:
    path: /opt/myapp
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: u=rwx,g=rx,o=rx

- name: Copy myapp files
  copy:
    src: "{{ playbook_dir }}/../myapp/"
    dest: /opt/myapp/
    owner: ec2-user
    group: ec2-user

- include_tasks: python-install.yml
- include_tasks: nginx-install.yml
