- name: Update apt cache
  apt:
    update_cache: yes
  when: ansible_os_family == "RedHat"

- name: Install system packages
  apt:
    name:
      - python3
      - python3-pip
      - python3-venv
      - nginx
    state: present

- name: Create app directory
  file:
    path: /opt/myapp
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'

- name: Copy Django app files
  copy:
    src: files/myapp/
    dest: /opt/myapp/
    owner: ubuntu
    group: ubuntu

- name: Install Python requirements
  pip:
    requirements: /opt/myapp/requirements.txt
    virtualenv: /opt/myapp/venv

- name: Create systemd service for Django
  template:
    src: django.service.j2
    dest: /etc/systemd/system/myapp.service
  notify: restart django

- name: Start Django service
  systemd:
    name: myapp
    enabled: yes
    state: started

- name: Configure nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/myapp
  notify: reload nginx

- name: Enable nginx site
  file:
    src: /etc/nginx/sites-available/myapp
    dest: /etc/nginx/sites-enabled/myapp
    state: link

- name: Remove default nginx config
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
