---
- name: Install Nginx
  dnf:
    name:
      - nginx
    state: present

- name: Configure Nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/myapp.conf
    owner: ec2-user
    group: ec2-user
    mode: '0644'
  notify: reload nginx

# - name: Enable site
#   file:
#     src: /etc/nginx/conf.d/myapp.conf
#     dest: /etc/nginx/sites-enabled/sample
#     state: link

# - name: Ensure Nginx is started and enabled
#   service:
#     name: nginx
#     state: started
#     enabled: true