---
- name: Install Nginx
  dnf:
    name:
      - nginx
    state: present

- name: Configure Nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/myapp.conf
    owner: ec2-user
    group: ec2-user
    mode: '0644'

# - name: Ensure nginx is started and enabled
#   systemd:
#     name: nginx
#     state: started
#     enabled: yes