- name: Template .env file
  template:
    src: env.j2
    dest: /opt/myapp/.env
    owner: ec2-user
    group: ec2-user
    mode: '0755'

- name: Run syncdb on the application
  community.general.django_manage:
    command: migrate
    project_path: /opt/myapp
    virtualenv: /opt/myapp/venv
  when: "'web-db-migrate' in group_names"

- name: Create an initial superuser
  community.general.django_manage:
    command: createsuperuser --noinput
    project_path: /opt/myapp
    virtualenv: /opt/myapp/venv
  when: "'web-db-migrate' in group_names"

- name: Run Django collectstatic
  community.general.django_manage:
    command: collectstatic --noinput
    project_path: /opt/myapp
    virtualenv: /opt/myapp/venv

- name: Configurate Django
  django_configurator:
    path_to_env_file: /opt/myapp/.env
    environment: prod
    additional_settings:
      DEVELOPMENT_MODE: True
  register: config_result

- name: Output Configuration Result
  debug:
    msg: "{{ config_result.msg }}"

- name: Restart gunicorn service
  systemd:
    name: gunicorn
    state: restarted

- name: Restart nginx service
  systemd:
    name: nginx
    state: restarted