---
- name: "Create app database"
  postgresql_db:
    name: "{{ db_name }}"
  become_user: postgres

- name: "Create db user"
  postgresql_user:
    state: present
    name: "{{ db_user }}"
    password: "{{ db_password }}"
  become_user: postgres

- name: GRANT ALL PRIVILEGES ON DATABASE to the user
  community.postgresql.postgresql_privs:
    login_db: "{{ db_name }}"
    privs: ALL
    type: database
    role: "{{ db_user }}"
  become_user: postgres

- name: GRANT ALL PRIVILEGES ON SCHEMA public to the user
  community.postgresql.postgresql_privs:
    login_db: "{{ db_name }}"
    privs: ALL
    type: schema
    objs: public
    role: "{{ db_user }}"
  become_user: postgres

- name: "Allow md5 connection for the db user"
  postgresql_pg_hba:
    dest: "~/data/pg_hba.conf"
    contype: host
    databases: all
    method: md5
    users: "{{ db_user }}"
    create: true
  become_user: postgres
  notify: restart postgres